###
POST http://localhost:9000/api/user/create HTTP/1.1
Content-Type: application/json

{"name":"Juanin","username":"admi2n@example.com", "password":"000000000"}

###
GET  http://localhost:9000/api/user/read/admin@example.com HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:9000/api/user/check/admin@example.com HTTP/1.1
Content-Type: application/json